// Estado inicial do organograma
const initialStateHTML = `
    <div class="node-container">
        <div class="node-group" style="padding-top: 0;">
            <div class="node-container" data-level="top">
                <div class="node-wrapper">
                    <div class="node">CEO | LEONARDO</div>
                    <div class="action-buttons">
                        <span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span>
                        <button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button>
                        <button class="action-button add-button" title="Adicionar Colaborador">+</button>
                    </div>
                </div>
                <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                <div class="node-group">
                    <!-- Nível 2: Diretores C-Level & CFO -->
                    <div class="node-container">
                        <div class="node-wrapper"><div class="node">CFO | KARINE</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                        <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                        <div class="node-group">
                            <div class="node-container">
                                <div class="node-wrapper"><div class="node secondary">FINANCEIRO |</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                                <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                            </div>
                        </div>
                    </div>
                    <div class="node-container">
                        <div class="node-wrapper"><div class="node">CMO | ROD L</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                        <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                        <div class="node-group">
                            <div class="node-container">
                                <div class="node-wrapper"><div class="node secondary">DIRETOR MARK | ROD C</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                                <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                                <div class="node-group">
                                    <div class="node-container"><div class="node-wrapper"><div class="node secondary">IS | JEFF</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                                    <div class="node-container"><div class="node-wrapper"><div class="node secondary">MARKETING DIGITAL</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                                    <div class="node-container"><div class="node-wrapper"><div class="node secondary">EDITOR | CAIO</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                                    <div class="node-container"><div class="node-wrapper"><div class="node secondary">UX</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="node-container">
                        <div class="node-wrapper"><div class="node">CPO | LUIZ</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                        <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                        <div class="node-group">
                            <div class="node-container">
                                <div class="node-wrapper"><div class="node secondary">CPO | GIOVANNI</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                                <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                                <div class="node-group">
                                    <div class="node-container"><div class="node-wrapper"><div class="node secondary">DIRETOR LOGISTICA | YURI & CAIO</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                                        <div class="node-group">
                                            <div class="node-container"><div class="node-wrapper"><div class="node secondary">EXPEDIÇÃO | 5 PESSOAS</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="node-container">
                        <div class="node-wrapper"><div class="node">VP EUROPA | ISSAC</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                        <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                        <div class="node-group">
                            <div class="node-container">
                                <div class="node-wrapper"><div class="node secondary">DIRETOR COMERCIAL | VINICIUS BRITO</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                                <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                                <div class="node-group">
                                    <div class="node-container">
                                        <div class="node-wrapper"><div class="node">CSS</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                                        <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                                        <div class="node-group">
                                            <div class="node-container"><div class="node-wrapper"><div class="node secondary">SUPORTE DSEC & PAGEUBIR | MARI</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                                            <div class="node-container"><div class="node-wrapper"><div class="node secondary">SUPORTE DSEC & PAGEUBIR | LARA</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                                            <div class="node-container"><div class="node-wrapper"><div class="node secondary">SUPORTE ALFRED | LUCAS</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="node-container">
                        <div class="node-wrapper"><div class="node">CTO | ARTHUR</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div>
                        <div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div>
                        <div class="node-group">
                            <div class="node-container"><div class="node-wrapper"><div class="node secondary">DEV PLENO | JOÃO</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                            <div class="node-container"><div class="node-wrapper"><div class="node secondary">DEV PLENO | JEFF</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                            <div class="node-container"><div class="node-wrapper"><div class="node secondary">DEV PLENO | LUCAS</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                            <div class="node-container"><div class="node-wrapper"><div class="node secondary">DEV JUNIOR | MACIEL</div><div class="action-buttons"><span class="goals-icon" title="Definir Metas"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg></span><button class="action-button edit-button" title="Editar Nome"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button class="action-button add-button" title="Adicionar Colaborador">+</button><button class="action-button remove-button" title="Remover Colaborador">-</button></div></div><div class="goals-modal"><h3>Metas</h3><textarea placeholder="Descreva as metas aqui..."></textarea></div></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
`;
